# Generated by Django 5.1.1 on 2024-09-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Philosopher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('school_of_thought', models.CharField(max_length=100)),
                ('core_ideas', models.JSONField(default=list)),
                ('tone', models.CharField(max_length=100)),
                ('works', models.JSONField(default=list)),
                ('era', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_philosopher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='philosophers.philosopher')),
            ],
        ),
    ]
