# Generated by Django 5.1.1 on 2024-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='philosopher',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='philosopher',
            name='quotes',
            field=models.JSONField(default=list),
        ),
    ]
